### PR TITLE
Proxy module.paths to resolve.paths

### PR DESCRIPTION
**Pull request by ColCh**
Related to #11

### CODE REVIEW

**Comment by ColCh** [comment]
Tests are passing on local dev machine. Any ideas why array keys are swapped \ reversed folder ?

``` shell
vagrant@vagrant-ubuntu-trusty-64:/vagrant/enhanced-require$ node --version
v0.10.25
```

**Comment by sokra** [comment]
I had no time to maintain enhanced-require for a while, and test are running on node.js 0.6 and 0.8... So no idea, maybe it succeed on travis node.js 0.10...

But when I merge this it would look like this repo is maintained. So I could only feel comfortable when I have time to at least upgrade the dependencies (enhanced-resolve dep is pretty old). So expect this to take at least 3 weeks until it get merged...

**Comment by ColCh** [comment]
Okay, no hurry :) 

I hope You're not deprecate this awesome module in future.

I will leave PR and Issue opened

**Comment by sokra** [comment]
> I hope You're not deprecate this awesome module in future.

Seems like a few people are using it. So "no". But I had no time to maintain it. webpack eats all my free time...

**Comment by ColCh** [comment]
Closing this PR due to possible legacy :)

**Pull request closed without merging**
